Map<String, bool> locationsMap = {
  "Corrientes": false,
  "Buenos Aires": false,
  "Catamarca": false,
  "Chaco": false,
  "Chubut": false,
  "Córdoba": false,
  "Entre Ríos": false,
  "Formosa": false,
  "Jujuy": false,
  "La Pampa": false,
  "La Rioja": false,
  "Mendoza": false,
  "Misiones": false,
  "Neuquén": false,
  "Río Negro": false,
  "Salta": false,
  "San Juan": false,
  "San Luis": false,
  "Santa Cruz": false,
  "Santa Fe": false,
  "Santiago del Estero": false,
  "Tierra del Fuego": false,
  "Tucumán": false,
};
